### ISSUE TITLE
IRC channel for reverse engineering discussions? #pine64-nutcracker on irc.pine64.org

### ISSUE THREAD

**Issue by WildCryptoFox** [pine64/bl602-re#5]
~~I've created the channel #pine64-ble602 on chat.freenode.net. If there is a better channel or network, please comment details below and I'll switch over.~~

**Comment by Avamander** [comment]
Pine64 has their own IRC server.

**Comment by gamelaster** [comment]
Hi @WildCryptoFox , the PINE64 have their own IRC server. We can host channel here.

**Comment by WildCryptoFox** [comment]
#pine64-nutcracker on irc.pine64.org (not yet created; but can be bridged to the matrix channel of the same name on matrix.org)
